import { Fragment } from 'react';
import Footer from '../../components/footer/Footer';
import Header from '../../components/header/Header';
import Scrollbar from '../../components/scrollbar/scrollbar';

const OverviewPage = () => {
	return (
		<Fragment>
			<div className="index_ico page_wrapper">
				<Header />

				<section className="page_header_overview page_header">
					<div className="container">
						<div class="container py-5">
							<div class="overview-section">
								<h1 class="mb-4">Coinlye Company Overview</h1>
								<p>
									<strong>Coinlye</strong> is a globally operating crypto
									staking and investment platform. The company runs a
									decentralized Web3 application built on the Binance Smart
									Chain (BNB Chain) to deliver high-yield returns to investors.
								</p>
								<p>
									Coinlye offers a daily ROI of <strong>1.5%–2%</strong> by
									deploying user funds in stablecoin liquidity farming pools.
									With registered offices in the United States and the United
									Kingdom, Coinlye emphasizes regulatory compliance (including
									FinCEN and FCA registrations) to establish trust and security
									in its services.
								</p>
							</div>

							<div class="overview-section">
								<h2>Mission and Vision</h2>
								<ul>
									<li>
										<p>
											<strong>Mission:</strong> Provide accessible, high-yield
											crypto investment opportunities globally through a secure
											and transparent platform. Empower investors by offering
											decentralized staking services that generate reliable
											daily returns while adhering to the highest compliance and
											security standards.
										</p>
									</li>

									<li>
										<p>
											<strong>Vision:</strong> Become the world’s most trusted
											decentralized investment partner, offering consistent
											returns and seamless staking experiences to users
											worldwide.
										</p>
									</li>
								</ul>
							</div>

							<div class="overview-section">
								<h2>Licensing and Compliance</h2>
								<p>
									Coinlye is fully licensed and regulated in its key markets. In
									the United States, the company is registered with the
									Financial Crimes Enforcement Network (FinCEN) as a Money
									Services Business (MSB), ensuring adherence to federal
									financial and anti-money-laundering regulations. In the United
									Kingdom, Coinlye is registered and regulated by the Financial
									Conduct Authority (FCA) for digital asset-related services.
									These registrations underscore Coinlye’s commitment to
									operating transparently and lawfully in the financial sector.
								</p>
							</div>

							<div class="overview-section">
								<h2>Services and Features</h2>
								<p>
									Coinlye offers a range of investment services designed for
									flexibility and growth:
								</p>
								<ul>
									<li>
										<strong>High-Yield Daily ROI:</strong> Investors can earn a
										fixed daily return of <strong>1.5%–2%</strong> on their
										crypto holdings through Coinlye’s staking platform. These
										returns are generated by yield farming using stablecoins,
										with rewards distributed daily via smart contracts. .
									</li>
									<li>
										<strong>
											Web3 Staking with Binance Wallet Integration:
										</strong>{' '}
										The platform is a Web3 application integrated with the
										Binance Chain Wallet and other compatible wallets. Users
										connect their own wallets to stake funds (USDT) on the BNB
										Smart Chain. This seamless setup particularly benefits users
										of the Binance ecosystem
									</li>
									<li>
										<strong>Low Minimum Investment:</strong> Coinlye allows a
										minimum investment of <strong>$10</strong>, making
										high-yield crypto staking accessible to a wide range of
										investors, including those with limited capital. .
									</li>
									<li>
										<strong>Liquidity Farming in Stablecoin:</strong> All
										invested funds are deployed in liquidity pools using the
										USDT stablecoin on the BNB Smart Chain. By focusing on USDT,
										Coinlye’s model reduces exposure to market volatility while
										harnessing DeFi liquidity farming to generate returns.
									</li>
									<li>
										<strong>Referral Program:</strong> The platform features a
										one-level referral program that rewards users for inviting
										others. Existing investors earn incentive bonuses based on
										the activity of referred participants, encouraging community
										growth.
									</li>
									<li>
										<strong>Decentralized and Transparent:</strong> All staking
										and reward distributions are executed through public smart
										contracts on the blockchain. Every transaction and balance
										is transparent and auditable onchain. Coinlye does not
										engage in lending or opaque investment schemes; instead, it
										relies on verifiable DeFi strategies to achieve its ROI.
									</li>
								</ul>
							</div>

							<div class="overview-section">
								<h2>Technology and Security</h2>
								<p>
									Coinlye’s platform is built on robust blockchain technology
									with security as a top priority:
								</p>
								<ul>
									<li>
										<strong>BNB Smart Chain Infrastructure:</strong> The
										platform leverages the Binance Smart Chain (BNB Chain)
										network for all staking and farming activities. BNB Chain is
										an established blockchain known for low fees, fast
										transactions, and compatibility with Ethereum smart
										contracts. This foundation provides a scalable and reliable
										environment for Coinlye’s services, while leveraging the
										broader Binance ecosystem architecture for additional
										security and resilience.
									</li>
									<li>
										<strong>Zero-Loss Investment Model:</strong> Coinlye
										emphasizes a 100% secure, zero-loss approach to protect
										investors’ principal. By staking only USDT in highly liquid
										liquidity pools, the platform minimizes exposure to market
										volatility, helping to safeguard user funds under normal
										conditions..
									</li>
									<li>
										<strong>Self-Custodied Wallets:</strong> Throughout the
										staking process, user assets remain in self-custody.
										Investors connect their own wallets and approve each staking
										transaction; Coinlye’s smart contracts handle the staking
										logic without ever taking custody of private keys. This
										ensures that only the user has control over the funds they
										deposit.
									</li>
									<li>
										<strong>Rigorous Security Practices:</strong> Coinlye
										employs industry-standard security measures, including
										audited smart contracts and encrypted transaction protocols.
										The platform’s registrations with FinCEN and the FCA also
										imply adherence to strict operational controls and
										oversight. Combined, these measures ensure that Coinlye’s
										architecture is resilient against fraud or tampering
									</li>
								</ul>
								<p>
									With this technology and security foundation, users can stake
									on Coinlye with confidence, knowing their funds are managed
									transparently and securely.
								</p>
							</div>

							<div class="overview-section">
								<h2>Target Market and Users</h2>
								<p>
									Coinlye is designed for a diverse global user base of crypto
									investors:
								</p>
								<ul>
									<li>
										<strong>Global Crypto Community:</strong> The platform
										serves international users seeking decentralized investment
										opportunities. Coinlye’s services are available worldwide,
										allowing anyone with internet access and a compatible wallet
										to participate.
									</li>
									<li>
										<strong>Binance Ecosystem Users:</strong> : Coinlye
										specifically targets users of the Binance ecosystem. By
										integrating directly with the Binance Chain Wallet and
										supporting BNB Coin, the platform appeals to Binance Chain
										and BNB holders looking for yield on their assets.
									</li>
									<li>
										<strong>Emerging Markets:</strong> The company places
										special emphasis on emerging markets such as Bangladesh,
										India, and parts of Africa and Southeast Asia. In these
										regions, demand for accessible and reliable crypto
										investment products is high. Coinlye’s low entry threshold
										and high-yield model are well-suited to investors in these
										fast-growing economies
									</li>
									<li>
										<strong>Crypto Enthusiasts and New Investors:</strong> With
										a low minimum investment and a straightforward earning
										model, Coinlye appeals to both experienced crypto users and
										newcomers. The platform provides educational materials and
										customer support to help users understand staking and
										maximize their returns.
									</li>
								</ul>
								<p>
									By serving this broad market, Coinlye aims to build a large
									and engaged user community that trusts the platform for
									consistent returns and transparency.
								</p>
							</div>

							<div class="overview-section">
								<h2>Office Locations</h2>
								<p>
									Coinlye maintains corporate offices in both the United States
									and the United Kingdom to support its international
									operations:
								</p>
								<ul>
									<li>
										<strong>United States Office:</strong> Sunshine Park, Floor
										05A, Sector-94, USA.
									</li>
									<li>
										<strong>United Kingdom Office:</strong> 12 Buckingham Rd,
										Thwaite, HG3 4TY, UK.
									</li>
								</ul>
								<p>
									These offices facilitate local compliance with financial
									regulations and provide regional support. The dual
									registration under U.S. and UK authorities, along with a
									physical presence in key markets, underscores Coinlye’s
									commitment to transparency, regulatory oversight, and customer
									service.
								</p>

								<p>
									In summary, Coinlye is a fully regulated crypto staking
									platform dedicated to delivering accessible, highyield
									investment opportunities to users around the world. Through
									its secure Web3 infrastructure on the Binance Smart Chain,
									robust licensing with FinCEN and the FCA, and emphasis on user
									self-custody, Coinlye offers investors a reliable daily ROI of{' '}
									<strong>1.5%–2%</strong>. The company’s clear mission, strong
									compliance foundation, and technology-driven approach position
									it as a trusted partner for modern cryptocurrency investors.
								</p>
							</div>
						</div>
					</div>
				</section>

				<Footer />
				<Scrollbar />
			</div>
		</Fragment>
	);
};
export default OverviewPage;
